version: '3.6'

services:
  smart-brain-api:
    container_name: smart-brain-back-end
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-back-end
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-back-end

  # Postgres
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sally
      POSTGRESS_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
